services:
    display.file.extension:
        class: AdminBundle\Extension\VichyTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Vich\UploaderBundle\Form\Type\VichFileType }
        arguments: [ "@vich_uploader.templating.helper.uploader_helper" ]

    admin.aws_s3.client:
        class: Aws\S3\S3Client
        actory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: latest
                credentials:
                    key: %amazon_key%
                    secret: %amazon_secret%
                region: eu-west-1

    admin.vich_uploader.dicrectory_namer:
        class: AdminBundle\Namer\VichDirectoryNamer
        public: true